### ISSUE TITLE
Segmentation fault with the last version of ARGoS

### ISSUE THREAD

**Issue by mbt925** [demiurge-project/argos3-epuck#11]
After the latest pull of ARGoS, I am getting a segmentation fault error when running a previously working project. The segmentation fault occurs after closing the simulator.

```
@ubuntu:~/argos3-examples$ argos3 -c experiments/obstacle_avoidance.argos 
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3core_simulator.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Not using threads
[INFO] Using random seed = 124
[INFO] Using simulation clock tick = 0.1
[INFO] Total experiment length in clock ticks = unlimited
[INFO] Loaded library "./build/controllers/obstacle_avoidance/libobstacle_avoidance.so"
Segmentation fault (core dumped)
```

GDB backtrace for the segfault:

```
(gdb) where
#0  0x00005555558661d8 in ?? ()
#1  0x00007ffff3248fb8 in argos::CBatteryEquippedEntity::~CBatteryEquippedEntity() () from /usr/local/lib/argos3/libargos3plugin_simulator_entities.so
#2  0x00007ffff3248fe0 in argos::CBatteryEquippedEntity::~CBatteryEquippedEntity() () from /usr/local/lib/argos3/libargos3plugin_simulator_entities.so
#3  0x00007ffff324e59b in void argos::CSpace::RemoveEntity<argos::CBatteryEquippedEntity>(argos::CBatteryEquippedEntity&) ()
   from /usr/local/lib/argos3/libargos3plugin_simulator_entities.so
#4  0x00007ffff324c383 in argos::CSpaceOperationRemoveCBatteryEquippedEntity::ApplyTo(argos::CSpace&, argos::CBatteryEquippedEntity&) ()
   from /usr/local/lib/argos3/libargos3plugin_simulator_entities.so
#5  0x00007ffff3250135 in void argos::CEntityOperation<argos::CSpaceOperationRemoveEntity, argos::CSpace, void>::Dispatch<argos::CBatteryEquippedEntity, argos::CSpaceOperationRemoveCBatteryEquippedEntity>(argos::CSpace&, argos::CEntity&)
    () from /usr/local/lib/argos3/libargos3plugin_simulator_entities.so
#6  0x00007ffff324e7d7 in void argos::CEntityOperation<argos::CSpaceOperationRemoveEntity, argos::CSpace, void>::Hook<argos::CBatteryEquippedEntity, argos::CSpaceOperationRemoveCBatteryEquippedEntity>(argos::CSpace&, argos::CEntity&) ()
   from /usr/local/lib/argos3/libargos3plugin_simulator_entities.so
#7  0x00007ffff7b2cd93 in void argos::CallEntityOperation<argos::CSpaceOperationRemoveEntity, argos::CSpace, void>(argos::CSpace&, argos::CEntity&) ()
   from /usr/local/lib/argos3/libargos3core_simulator.so
#8  0x00007fffe9bd07e3 in argos::CSpaceOperationRemoveCEPuckEntity::ApplyTo(argo---Type <return> to continue, or q <return> to quit---
s::CSpace&, argos::CEPuckEntity&) ()
   from /usr/local/lib/argos3/libargos3plugin_simulator_epuck.so
#9  0x00007fffe9bd3e6b in void argos::CEntityOperation<argos::CSpaceOperationRemoveEntity, argos::CSpace, void>::Dispatch<argos::CEPuckEntity, argos::CSpaceOperationRemoveCEPuckEntity>(argos::CSpace&, argos::CEntity&) ()
   from /usr/local/lib/argos3/libargos3plugin_simulator_epuck.so
#10 0x00007fffe9bd230b in void argos::CEntityOperation<argos::CSpaceOperationRemoveEntity, argos::CSpace, void>::Hook<argos::CEPuckEntity, argos::CSpaceOperationRemoveCEPuckEntity>(argos::CSpace&, argos::CEntity&) ()
   from /usr/local/lib/argos3/libargos3plugin_simulator_epuck.so
#11 0x00007ffff7b2cd93 in void argos::CallEntityOperation<argos::CSpaceOperationRemoveEntity, argos::CSpace, void>(argos::CSpace&, argos::CEntity&) ()
   from /usr/local/lib/argos3/libargos3core_simulator.so
#12 0x00007ffff7b74b9d in argos::CSpace::Destroy() ()
   from /usr/local/lib/argos3/libargos3core_simulator.so
#13 0x00007ffff7b2fe30 in argos::CSimulator::Destroy() ()
   from /usr/local/lib/argos3/libargos3core_simulator.so
#14 0x0000555555570b85 in main ()
```

**Comment by mbt925** [comment]
I uploaded my sample [here](https://files.fm/u/zt56t6sd).
